common_lib := lib/common.sh
scripts: test steps/declarativesystems/AwsCli/onExecute.sh steps/declarativesystems/GoReleaser/onExecute.sh steps/declarativesystems/PodmanPushAwsEcr/onExecute.sh steps/declarativesystems/NpmBuild/onExecute.sh steps/declarativesystems/NpmPublish/onExecute.sh

steps/declarativesystems/AwsCli/onExecute.sh:
	echo "# =====[DO NOT EDIT THIS FILE]=====" > steps/declarativesystems/AwsCli/onExecute.sh
	cat $(common_lib) >> steps/declarativesystems/AwsCli/onExecute.sh
	cat steps/declarativesystems/AwsCli/src/onExecute.sh >> steps/declarativesystems/AwsCli/onExecute.sh

steps/declarativesystems/GoReleaser/onExecute.sh:
	echo "# =====[DO NOT EDIT THIS FILE]=====" > steps/declarativesystems/GoReleaser/onExecute.sh
	cat $(common_lib) >> steps/declarativesystems/GoReleaser/onExecute.sh
	cat steps/declarativesystems/GoReleaser/src/onExecute.sh >> steps/declarativesystems/GoReleaser/onExecute.sh

steps/declarativesystems/PodmanPushAwsEcr/onExecute.sh:
	echo "# =====[DO NOT EDIT THIS FILE]=====" > steps/declarativesystems/PodmanPushAwsEcr/onExecute.sh
	cat $(common_lib) >> steps/declarativesystems/PodmanPushAwsEcr/onExecute.sh
	cat steps/declarativesystems/PodmanPushAwsEcr/src/onExecute.sh >> steps/declarativesystems/PodmanPushAwsEcr/onExecute.sh

steps/declarativesystems/NpmBuild/onExecute.sh:
	echo "# =====[DO NOT EDIT THIS FILE]=====" > steps/declarativesystems/NpmBuild/onExecute.sh
	cat $(common_lib) >> steps/declarativesystems/NpmBuild/onExecute.sh
	cat steps/declarativesystems/NpmBuild/src/onExecute.sh >> steps/declarativesystems/NpmBuild/onExecute.sh

steps/declarativesystems/NpmPublish/onExecute.sh:
	echo "# =====[DO NOT EDIT THIS FILE]=====" > steps/declarativesystems/NpmPublish/onExecute.sh
	cat $(common_lib) >> steps/declarativesystems/NpmPublish/onExecute.sh
	cat steps/declarativesystems/NpmPublish/src/onExecute.sh >> steps/declarativesystems/NpmPublish/onExecute.sh

clean:
	rm -f steps/declarativesystems/AwsCli/onExecute.sh
	rm -f steps/declarativesystems/GoReleaser/onExecute.sh
	rm -f steps/declarativesystems/PodmanPushAwsEcr/onExecute.sh
	rm -f steps/declarativesystems/NpmBuild/onExecute.sh
	rm -f steps/declarativesystems/NpmPublish/onExecute.sh

test:
	echo "=== bash syntax ==="
	find . -iname '*.sh' -exec bash -n {} \;

	echo "=== yaml syntax ==="
	./res/validate_yaml.py