IMAGE_TAG := 0.0.1-1
IMAGE_NAME := declarativesystems.jfrog.io/docker/docker-local/pipelines
IMAGE_VERSION := $(IMAGE_NAME):$(IMAGE_TAG)


COMMON_LIB := lib/common.sh

COMPILED_SCRIPTS := steps/declarativesystems/AwsCli/onExecute.sh
COMPILED_SCRIPTS += steps/declarativesystems/GoReleaser/onExecute.sh
COMPILED_SCRIPTS += steps/declarativesystems/NpmBuild/onExecute.sh
COMPILED_SCRIPTS += steps/declarativesystems/NpmPublish/onExecute.sh
COMPILED_SCRIPTS += steps/declarativesystems/PipInstall/onExecute.sh
COMPILED_SCRIPTS += steps/declarativesystems/PodmanPushAwsEcr/onExecute.sh
COMPILED_SCRIPTS += steps/declarativesystems/PythonWheelDeploy/onExecute.sh

scripts: test $(COMPILED_SCRIPTS)

steps/declarativesystems/AwsCli/onExecute.sh:
	echo "# =====[DO NOT EDIT THIS FILE]=====" > steps/declarativesystems/AwsCli/onExecute.sh
	cat $(COMMON_LIB) >> steps/declarativesystems/AwsCli/onExecute.sh
	cat steps/declarativesystems/AwsCli/src/onExecute.sh >> steps/declarativesystems/AwsCli/onExecute.sh

steps/declarativesystems/GoReleaser/onExecute.sh:
	echo "# =====[DO NOT EDIT THIS FILE]=====" > steps/declarativesystems/GoReleaser/onExecute.sh
	cat $(COMMON_LIB) >> steps/declarativesystems/GoReleaser/onExecute.sh
	cat steps/declarativesystems/GoReleaser/src/onExecute.sh >> steps/declarativesystems/GoReleaser/onExecute.sh

steps/declarativesystems/PipInstall/onExecute.sh:
	echo "# =====[DO NOT EDIT THIS FILE]=====" > steps/declarativesystems/PipInstall/onExecute.sh
	cat $(COMMON_LIB) >> steps/declarativesystems/PipInstall/onExecute.sh
	cat steps/declarativesystems/PipInstall/src/onExecute.sh >> steps/declarativesystems/PipInstall/onExecute.sh

steps/declarativesystems/PodmanPushAwsEcr/onExecute.sh:
	echo "# =====[DO NOT EDIT THIS FILE]=====" > steps/declarativesystems/PodmanPushAwsEcr/onExecute.sh
	cat $(COMMON_LIB) >> steps/declarativesystems/PodmanPushAwsEcr/onExecute.sh
	cat steps/declarativesystems/PodmanPushAwsEcr/src/onExecute.sh >> steps/declarativesystems/PodmanPushAwsEcr/onExecute.sh

steps/declarativesystems/NpmBuild/onExecute.sh:
	echo "# =====[DO NOT EDIT THIS FILE]=====" > steps/declarativesystems/NpmBuild/onExecute.sh
	cat $(COMMON_LIB) >> steps/declarativesystems/NpmBuild/onExecute.sh
	cat steps/declarativesystems/NpmBuild/src/onExecute.sh >> steps/declarativesystems/NpmBuild/onExecute.sh

steps/declarativesystems/NpmPublish/onExecute.sh:
	echo "# =====[DO NOT EDIT THIS FILE]=====" > steps/declarativesystems/NpmPublish/onExecute.sh
	cat $(COMMON_LIB) >> steps/declarativesystems/NpmPublish/onExecute.sh
	cat steps/declarativesystems/NpmPublish/src/onExecute.sh >> steps/declarativesystems/NpmPublish/onExecute.sh

steps/declarativesystems/PythonWheelDeploy/onExecute.sh:
	echo "# =====[DO NOT EDIT THIS FILE]=====" > steps/declarativesystems/PythonWheelDeploy/onExecute.sh
	cat $(COMMON_LIB) >> steps/declarativesystems/PythonWheelDeploy/onExecute.sh
	cat steps/declarativesystems/PythonWheelDeploy/src/onExecute.sh >> steps/declarativesystems/PythonWheelDeploy/onExecute.sh

clean:
	rm -f steps/declarativesystems/*/onExecute.sh

test:
	echo "=== bash syntax ==="
	bash -n lib/common.sh
	find . -iname '*.sh' -print0 | xargs -0L1 bash -n

	echo "=== yaml syntax ==="
	./res/validate_yaml.py

image:
	cd images/pipelines && podman build . -t $(IMAGE_VERSION)

shell:
	podman run --rm -v $(shell pwd):/mnt -ti $(IMAGE_VERSION) /bin/bash

print_image_name:
	@echo $(IMAGE_NAME)

print_image_tag:
	@echo $(IMAGE_TAG)